
LOGIN_USERNAME = "#user-name"
LOGIN_PASSWORD = "#password"
LOGIN_BUTTON = "#login-button"
ERROR_MESSAGE = ".error-message-container"
INVENTORY_TITLE =  "[data-test='title']"
APP_LOGO_TITLE = ".app_logo"
APP_LOGO_NAME = "Swag Labs"
# INVENTORY_TITLE = ".title"
CHECKOUT_OVERVIEW_TITLE = "[data-test='title']"
CHECKOUT_COMPLETE_TITLE = "[data-test='title']"
BACK_HOME_BUTTON = "#back-to-products"
ENDPOINT_AFTER_LOGIN = "inventory"
MENU_BUTTON = "#react-burger-menu-btn"
LOGOUT_LINK = "#logout_sidebar_link"
ADD_TO_CART_BUTTON = "text=Add to cart"
REMOVE_BUTTON = "text=Remove"
CART_BADGE = ".shopping_cart_badge"
CART_LINK = ".shopping_cart_link"
CHECKOUT_BUTTON = "text=Checkout"
CONTINUE_SHOPPING_BUTTON = ".continue-shopping"
CART_ITEMS = ".cart_item"
SORT_DROPDOWN = ".product_sort_container"
FIRST_ITEM_NAME = ".inventory_item_name"
SORT_DROPDOWN_OPTION_1 = "za"
SORT_DROPDOWN_OPTION_2 = "lohi"
FIRST_NAME_INPUT = "input[data-test='firstName']"
LAST_NAME_INPUT = "input[data-test='lastName']"
POSTAL_CODE_INPUT = "input[data-test='postalCode']"
CONTINUE_BUTTON = "input[data-test='continue']"
FINISH_BUTTON = "button[data-test='finish']"
CANCEL_BUTTON = "button[data-test='cancel']"
LOGIN_ERROR_MESSAGE_1 = "Sorry, this user has been locked out"
LOGIN_ERROR_MESSAGE_2 = "Username and password do not match any user in this service"
ENDPOINT_CART = "cart"